version: "3.7"
services:
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - 9000:80
  php-fpm:
    build:
      context: .
      dockerfile: ./docker/php-fpm/Dockerfile
      target: dev
    working_dir: /var/www
    volumes:
      - .:/var/www
    environment:
      TZ: ${APP_TIMEZONE}
  mysql:
    image: mysql:8
    volumes:
      - .:/var/www
      - ./volumes/mysql:/var/lib/mysql
    environment:
      TZ: ${APP_TIMEZONE}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    command: [
      '--character-set-server=utf8',
      '--collation-server=utf8_unicode_ci',
      '--default-authentication-plugin=mysql_native_password',
    ]
    ports:
      - 3308:3306
